#!/usr/bin/env python3
"""Generate the checked-in Kotlin TDLib declaration inventory from td_api.tl."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "core" / "raw" / "td_api.tl"
DEFAULT_LOCK = ROOT / "core" / "raw" / "tdlib.lock.json"
DEFAULT_OUTPUT = ROOT / "core-tdlib" / "src" / "main" / "kotlin" / "org" / "vibetgram" / "core" / "tdlib" / "generated" / "TdlibTypes.kt"
DECLARATION = re.compile(r"^(?P<name>[A-Za-z][A-Za-z0-9_]*)\b.*=\s*(?P<result>[^;]+);$")


def parse_names(source: str) -> tuple[list[str], list[str]]:
    constructors: list[str] = []
    functions: list[str] = []
    in_functions = False
    for raw_line in source.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue
        if line == "---functions---":
            in_functions = True
            continue
        if line.startswith("---"):
            continue
        match = DECLARATION.match(line)
        if not match:
            raise ValueError(f"invalid td_api.tl declaration: {line!r}")
        name = match.group("name")
        if not in_functions and ("?" in line or name == "vector"):
            continue
        (functions if in_functions else constructors).append(name)
    if not functions:
        raise ValueError("td_api.tl has no functions")
    return sorted(constructors), sorted(functions)


def kotlin_string(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def render(constructors: list[str], functions: list[str], commit: str, schema_hash: str, source_hash: str) -> str:
    def set_literal(items: list[str]) -> str:
        lines = ["setOf("] + [f"        {kotlin_string(item)}," for item in items] + ["    )"]
        return "\n".join(lines)

    return f'''// Generated by scripts/generate-tdlib-kotlin.py; do not edit.\npackage org.vibetgram.core.tdlib.generated\n\n/** Exact identity and declaration inventory of the pinned td_api.tl. */\nobject GeneratedTdlibSchema {{\n    const val TD_LIB_COMMIT: String = {kotlin_string(commit)}\n    const val TD_API_TL_SHA256: String = {kotlin_string(source_hash)}\n    const val SCHEMA_HASH: String = {kotlin_string(schema_hash)}\n    const val GENERATOR_VERSION: String = "1.0.0"\n\n    val constructors: Set<String> = {set_literal(constructors)}\n\n    val functions: Set<String> = {set_literal(functions)}\n}}\n\n/** Typed generated bootstrap functions used by the Kotlin adapter. */\nsealed interface GeneratedTdFunction {{\n    data class GetChats(val offsetChatId: Long, val limit: Int) : GeneratedTdFunction\n    data class GetChatHistory(val chatId: Long, val fromMessageId: Long, val limit: Int) : GeneratedTdFunction\n    data class SendMessage(\n        val chatId: Long,\n        val text: String,\n        val replyToMessageId: Long?,\n        val disableNotification: Boolean,\n    ) : GeneratedTdFunction\n}}\n'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    source_bytes = args.source.read_bytes()
    lock = json.loads(args.lock.read_text(encoding="utf-8"))
    source_hash = hashlib.sha256(source_bytes).hexdigest()
    if source_hash != lock["td_api_tl_sha256"]:
        raise SystemExit("td_api.tl does not match tdlib.lock.json")
    constructors, functions = parse_names(source_bytes.decode("utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render(constructors, functions, lock["tdlib_commit"], lock["schema_hash"], source_hash),
        encoding="utf-8",
    )
    print(f"Generated {len(constructors)} constructors and {len(functions)} functions")
    print(f"schema_hash={lock['schema_hash']}")


if __name__ == "__main__":
    main()
